### ISSUE TITLE
Support for Doctrine ORM 3.0

### ISSUE THREAD

**Issue by r3hp1c** [DoctrineEncryptBundle/DoctrineEncryptBundle#20]
We need to have a look at this when Doctrime ORM 3.0 has been released.

We will probably need to drop support for Annotations as it has been deprecated and will also not be supported ORM 3.0: https://www.doctrine-project.org/projects/doctrine-orm/en/latest/reference/basic-mapping.html

**Comment by vstudioseu** [comment]
Any progress for this?

**Comment by ndench** [comment]
I see we have a proposal for 6.0 #29 which includes support for Doctrine 3 support.

**Comment by r3hp1c** [comment]
Progress have been slow as I have not been able to make a lot of time to get this done correctly as suggested in https://github.com/DoctrineEncryptBundle/DoctrineEncryptBundle/pull/29#issuecomment-1984375617

I hope to have a little more time this coming week to make some progress, probably start a few discussions for the project as well.

**Comment by subiabre** [comment]
Hi @r3hp1c is there something we can help with to push the support form ORM 3.0 ?

**Comment by r3hp1c** [comment]
Hi @subiabre 

I have been struggling to make time to get my proposed #29 pull request done the more correct way as suggested in the pull request comment https://github.com/DoctrineEncryptBundle/DoctrineEncryptBundle/pull/29#issuecomment-1984375617

The main problem I have been facing is to get the commands working for the current version 5.4 and the proposed version 6 merged and working correctly.

I am starting to think I should release version 6 with a release note that it is a rewrite and completely breaks backwards compatibility.  
@Zombaya please see what I will probably end up doing.

**Comment by lambstream** [comment]
+1 for moving to doctrine types and having a BC break. This would be fine for my specific use case. I don't know if this would  cause major issues for other people however.

**Comment by danardf** [comment]
Hi everyone.

I'd like to know when this bundle will be ready? 
I'm waiting for Doctrime ORM 3.0 compatibility indeed.
Have a good weekend

**Comment by r3hp1c** [comment]
Thanks @Zombaya merged #39 and released version 5.4.2. Closing as ORM 3.x should now be supported
